server:
  port: 8082

spring:
  application:
    name: collector-service
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skyi_collector?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      # 重试次数
      retries: 3
      # 批量大小
      batch-size: 16384
      # 缓冲区大小
      buffer-memory: 33554432
      # 幂等性
      properties:
        enable.idempotence: true
      # 关键字段序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值序列化，使用JSON序列化器
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: collector-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.skyi.collector.dto,com.skyi.common.model

# XXL-JOB配置
xxl:
  job:
    enabled: false  # 禁用XXL-Job
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: collector-service-executor
      ip: 
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

# 采集器配置
collector:
  # Kafka配置
  kafka:
    enabled: true
    topics:
      metric-data: collector-metric-data
      collection-status: collector-status
  
  # 服务器采集配置
  server:
    enabled: true
    protocols:
      - snmp
      - ssh
    defaultInterval: 60  # 默认采集间隔(秒)
  
  # 数据库采集配置
  database:
    enabled: true
    protocols:
      - jdbc
    defaultInterval: 300  # 默认采集间隔(秒)
  
  # 中间件采集配置
  middleware:
    enabled: true
    protocols:
      - http
      - jmx
    defaultInterval: 120  # 默认采集间隔(秒)
  
  # 应用采集配置
  application:
    enabled: true
    protocols:
      - http
      - prometheus
    defaultInterval: 60  # 默认采集间隔(秒)

# 日志配置
logging:
  level:
    com.skyi: info
    org.hibernate.SQL: debug
    org.apache.kafka: warn 